# Generated by Django 3.1.3 on 2020-11-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('address_line1', models.CharField(max_length=255, null=True)),
                ('address_line2', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('zipcode', models.IntegerField(null=True)),
                ('menu_item1', models.CharField(max_length=255, null=True)),
                ('menu_item2', models.CharField(max_length=255, null=True)),
                ('menu_item3', models.CharField(max_length=255, null=True)),
                ('delivery_pickup', models.CharField(max_length=255, null=True)),
                ('payment_method', models.CharField(max_length=255, null=True)),
                ('password1', models.CharField(max_length=255, null=True)),
                ('password2', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
