# Generated by Django 3.1.3 on 2020-11-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=255)),
                ('dish_image', models.ImageField(upload_to='')),
                ('dish_price', models.FloatField()),
                ('dish_calories', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_pickup',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Takeout', 'Takeout')], default='Takeout', max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu_item1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu_item2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu_item3',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
