# Generated by Django 3.1.3 on 2020-11-22 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takeout', '0004_auto_20201122_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='takeout.image'),
        ),
    ]
