# Generated by Django 3.1.3 on 2020-11-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeout', '0005_auto_20201122_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
