# Generated by Django 3.1.3 on 2020-11-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeout', '0007_auto_20201122_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dish_image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
