# Generated by Django 3.1.3 on 2020-11-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeout', '0008_auto_20201122_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dish_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
